/**
 * Characters, locations, projects and character relations.
 *
 * FOUR top-level prefixes — `/api/characters`, `/api/locations`, `/api/projects`,
 * `/api/character-relations` — per architecture.html §4.4 and §5.2. There is no
 * `/api/registry` prefix: the nine route modules are a file layout, not a URL layout,
 * and this one owns four URLs.
 *
 * ONE ROUTER PER PREFIX, each mounted exactly once in `app.ts`. A single shared instance
 * mounted four times does not work: `Hono.route()` COPIES the sub-app's route table under
 * the prefix it is given, so one `GET /:id` registered here would answer under all four
 * and `/api/locations/char_lazaro` would reach the character handler. The four entities
 * have near-identical URL shapes, so the aliasing stays invisible until it serves the
 * wrong row.
 *
 * P3.6.4 fills in the READS — a list and a `/:id` for each of the four. Full registry CRUD
 * (driven by the event side panel, §5.2) lands in P12.
 *
 * ── THE FOUR READS ARE THE SAME READ, FOUR TIMES ──────────────────────────────────────
 * List: every row of one table in the active save, ordered by name with the id as
 * tiebreak. Detail: one row BY (save, id), 404 if it is not in that save. They are
 * written out four times rather than generated from a table descriptor because the
 * generic version would have to be typed over Drizzle's table shapes to keep
 * `dropNulls` returning the right entity, and the abstraction would be longer and less
 * readable than the four copies it replaced. The one thing they genuinely share —
 * `resolveSave` and `dropNulls` — is imported.
 *
 * ── THE WIRE FORMAT IS camelCase ──────────────────────────────────────────────────────
 * SQL columns are snake_case and stay inside `db/schema.ts`; Drizzle's inferred row types
 * are already camelCase, so these handlers return them VERBATIM (the wire-format
 * decision). The one adjustment is nullability — `dropNulls`, see `common.ts`.
 */
import { and, asc, eq } from 'drizzle-orm';
import { Hono } from 'hono';

import type { Character, CharacterRelation, Location, Project } from '@shared/types/index';

import { db } from '../db/index.js';
import { character, characterRelation, location, project } from '../db/schema.js';

import { dropNulls, resolveSave } from './common.js';

export type CharactersResponse = { characters: Character[] };
export type CharacterResponse = { character: Character };
export type LocationsResponse = { locations: Location[] };
export type LocationResponse = { location: Location };
export type ProjectsResponse = { projects: Project[] };
export type ProjectResponse = { project: Project };
export type CharacterRelationsResponse = { characterRelations: CharacterRelation[] };
export type CharacterRelationResponse = { characterRelation: CharacterRelation };

export const characterRoutes = new Hono();
export const locationRoutes = new Hono();
export const projectRoutes = new Hono();
export const characterRelationRoutes = new Hono();

/* ------------------------------------------------------------------------------------ *
 * /api/characters
 * ------------------------------------------------------------------------------------ */

/**
 * `GET /api/characters` — the save's cast, ordered by name.
 *
 * `character.name` has no UNIQUE constraint (two people may share a name, and canon has
 * mononyms), so the id is appended as a tiebreak to make the order TOTAL. Without it two
 * same-named rows come back in whatever order the query planner picked, which is stable
 * until it isn't and shows up as a list that reshuffles between loads.
 */
characterRoutes.get('/', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const rows = db
    .select()
    .from(character)
    .where(eq(character.saveId, scope.saveId))
    .orderBy(asc(character.name), asc(character.id))
    .all();

  const characters: Character[] = rows.map(dropNulls);
  return c.json({ characters } satisfies CharactersResponse);
});

/**
 * `GET /api/characters/:id` — one character, LOOKED UP WITHIN THE SAVE.
 *
 * `character.id` is a bare primary key, so a lookup by id alone would happily return a
 * row belonging to another save — and every registry id is regenerated by a fork (§2.6),
 * which makes "the right id in the wrong save" the normal failure rather than an exotic
 * one. The save is part of the WHERE on every detail read below for that reason, and a
 * miss is a 404 naming both halves.
 */
characterRoutes.get('/:id', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const id = c.req.param('id');
  const row = db
    .select()
    .from(character)
    .where(and(eq(character.saveId, scope.saveId), eq(character.id, id)))
    .get();

  if (row === undefined) {
    return c.json({ error: `no character with id '${id}' in save '${scope.saveId}'` }, 404);
  }

  return c.json({ character: dropNulls(row) } satisfies CharacterResponse);
});

/* ------------------------------------------------------------------------------------ *
 * /api/locations
 * ------------------------------------------------------------------------------------ */

/**
 * `GET /api/locations` — every place in the save, ordered by name.
 *
 * EVERY STAGE OF A RENAME CHAIN IS ITS OWN ROW AND ALL OF THEM ARE HERE. "COP Isotope",
 * "FOB Oasis", "Camp Oasis", "Oasis City" and "Star City" are five rows linked by
 * `supersededByLocationId` (§2.2), not one row with a history, and this endpoint does not
 * collapse them: an event sited at "FOB Oasis" has to render under the name it had at the
 * time. Resolving to the canonical head is a MEMBERSHIP operation and lives in
 * `resolveTimeline`'s `byLocation` predicate (P3.5.4) — the chain itself is on the wire so
 * the client can walk it when it needs the head.
 */
locationRoutes.get('/', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const rows = db
    .select()
    .from(location)
    .where(eq(location.saveId, scope.saveId))
    .orderBy(asc(location.name), asc(location.id))
    .all();

  const locations: Location[] = rows.map(dropNulls);
  return c.json({ locations } satisfies LocationsResponse);
});

/** `GET /api/locations/:id` — one place, looked up within the save. */
locationRoutes.get('/:id', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const id = c.req.param('id');
  const row = db
    .select()
    .from(location)
    .where(and(eq(location.saveId, scope.saveId), eq(location.id, id)))
    .get();

  if (row === undefined) {
    return c.json({ error: `no location with id '${id}' in save '${scope.saveId}'` }, 404);
  }

  return c.json({ location: dropNulls(row) } satisfies LocationResponse);
});

/* ------------------------------------------------------------------------------------ *
 * /api/projects
 * ------------------------------------------------------------------------------------ */

/**
 * `GET /api/projects` — the save's programmes, ordered by name.
 *
 * `dateStart` / `dateEnd` travel with their PRECISION columns and are never formatted
 * here (§2.3, render-by-precision): "Expected 2086" is year precision, and the instant
 * stored beside it is a January-1 placeholder that no view may print.
 */
projectRoutes.get('/', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const rows = db
    .select()
    .from(project)
    .where(eq(project.saveId, scope.saveId))
    .orderBy(asc(project.name), asc(project.id))
    .all();

  const projects: Project[] = rows.map(dropNulls);
  return c.json({ projects } satisfies ProjectsResponse);
});

/** `GET /api/projects/:id` — one programme, looked up within the save. */
projectRoutes.get('/:id', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const id = c.req.param('id');
  const row = db
    .select()
    .from(project)
    .where(and(eq(project.saveId, scope.saveId), eq(project.id, id)))
    .get();

  if (row === undefined) {
    return c.json({ error: `no project with id '${id}' in save '${scope.saveId}'` }, 404);
  }

  return c.json({ project: dropNulls(row) } satisfies ProjectResponse);
});

/* ------------------------------------------------------------------------------------ *
 * /api/character-relations
 * ------------------------------------------------------------------------------------ */

/**
 * `GET /api/character-relations` — the family graph's stored edges.
 *
 * ORDERED BY THE EDGE, NOT BY THE ID. `character_relation.id` is a generated string that
 * sorts arbitrarily and the table has no name column, so the only ordering with meaning
 * to a reader is the edge itself — and `(saveId, from, to, type)` is UNIQUE, which makes
 * it total.
 *
 * WHAT IS NOT HERE: the DERIVED edges. Two characters sharing a `parent-of` parent are
 * siblings by construction and canon's Adan–X pair is deliberately not stored (P3.2.5);
 * Family Trees derives it (P14.5). This endpoint answers what was AUTHORED, and a
 * synthesized sibling row here would be indistinguishable from one somebody wrote.
 */
characterRelationRoutes.get('/', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const rows = db
    .select()
    .from(characterRelation)
    .where(eq(characterRelation.saveId, scope.saveId))
    .orderBy(
      asc(characterRelation.fromCharacterId),
      asc(characterRelation.toCharacterId),
      asc(characterRelation.type),
    )
    .all();

  const characterRelations: CharacterRelation[] = rows.map(dropNulls);
  return c.json({ characterRelations } satisfies CharacterRelationsResponse);
});

/** `GET /api/character-relations/:id` — one edge, looked up within the save. */
characterRelationRoutes.get('/:id', (c) => {
  const scope = resolveSave(c.req.query('save'));
  if (!scope.ok) return c.json({ error: scope.error }, scope.status);

  const id = c.req.param('id');
  const row = db
    .select()
    .from(characterRelation)
    .where(and(eq(characterRelation.saveId, scope.saveId), eq(characterRelation.id, id)))
    .get();

  if (row === undefined) {
    return c.json(
      { error: `no character relation with id '${id}' in save '${scope.saveId}'` },
      404,
    );
  }

  return c.json({ characterRelation: dropNulls(row) } satisfies CharacterRelationResponse);
});
